FROM temafey/alpine-php:7.1
ARG USER=root
ARG PASSWORD=root
ARG COMPOSER_VERSION=1.8.0
RUN apk add -U --no-cache \
        php7-pear \
        openssh \
        supervisor \
        autoconf \
        git \
        nano \
        curl \
        wget \
        apache-ant \
        zip \
        php7-xdebug \
    && rm -rf /var/cache/apk/* \
    && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
    && echo "${USER}:${PASSWORD}" | chpasswd \
    && ssh-keygen -A \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION} \
    && composer global require "hirak/prestissimo:0.3.7" \
    && wget https://psysh.org/psysh \
    && chmod +x psysh \
    && mv psysh /usr/bin/psysh
COPY devfs /
RUN HOST_IP="$(/sbin/ip route|awk '/default/ { print $3 }')" \
    && sed -i "$ a\xdebug.remote_host=${HOST_IP}" /etc/php7/conf.d/xdebug.ini \
    && sed -i "s|xdebug.remote_autostart=1|xdebug.remote_autostart=0|g" /etc/php7/conf.d/00_xdebug.ini
CMD ["supervisord", "--nodaemon", "--configuration", "/etc/supervisor/conf.d/supervisord.conf"]

EXPOSE 22 9000
